name: GitHub Actions Demo
#run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: push
jobs:
  Explore-GitHub-Actions:
runs-on: ubuntu-latest
steps:
  #â€“ name: Check out repository code
    uses: actions/checkout@v2
  - name: List files in the repository
    run: ls ${{ github.workspace }}
    run: echo â€œThis jobâ€™s status is ${{ job.status }}.â€
